ptr=start;
if(start==NULL)
    return;
while(ptr->next!=NULL)
{
    if((ptr->data==ptr->next->data)&&(ptr->next->next==NULL)||(ptr->next->next->data!=ptr->data))
    {
        ptr1=ptr1->next->next;
        free(ptr->next);
        ptr->next=ptr1;
    }
    else
        ptr=ptr->next;
}